name: Shared Node CI

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '22.x'
      test-command:
        type: string
        default: 'npm test'
      run-build:
        type: boolean
        default: true
      build-command:
        type: string
        default: 'npm run build'
      artifact-name:
        type: string
        default: 'app-dist'
      artifact-path:
        type: string
        default: 'dist/'
      target-env:
        type: string
        default: 'staging'

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm' 
      - run: npm ci
      - run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    # accès aux secrets
    environment: ${{ inputs.target-env }}
    
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: ${{ inputs.test-command }}
      
      # valider le masquage du secret
      - name: Vérification du masquage du secret
        run: echo "Le secret API est $API_KEY"
        env:
          API_KEY: ${{ secrets.STAGING_API_KEY }}

  build:
    name: Build & Artifact
    if: ${{ inputs.run-build == true }}
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: ${{ inputs.build-command }}
      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}